### ISSUE TITLE
Setting LC_ALL doesn't work for R-IDE

### ISSUE THREAD

**Issue by amirmasoudabdol** [REditorSupport/sublime-ide-r#13]
I'm wondering why I get this error when trying to "Clean and Build" using R-Box. I don't have this issue on RStudio or when I ran R from the terminal and it only appears inside Sublime. I've followed [this](https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c#17510093) instruction but it appears to be ineffective. I'm running macOS Mojave.

```
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
```

**Comment by amirmasoudabdol** [comment]
Do you have any ideas on how to bypass this warning when compiling from Sublime Text?

**Comment by randy3k** [comment]
What OS are you currently on?

**Comment by amirmasoudabdol** [comment]
I'm using macOS Mojave.

**Comment by randy3k** [comment]
Sorry. I must be blind. You mentioned it in the original post.

**Comment by randy3k** [comment]
I believe you could create `~.Renviron ` and put 
```
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

PS: untested

**Comment by amirmasoudabdol** [comment]
Thanks! That is actually working. It's interesting that the usual suspect `.Rprofile` doesn't work, either setting the bash values.
