### ISSUE TITLE
Feature request: Support python syntax highlighting in Rmd documents

### ISSUE THREAD

**Issue by adibender** [REditorSupport/sublime-ide-r#23]
Thx to **`reticulate`** (https://github.com/rstudio/reticulate) it is now possible to include python chunks into 
Rmarkdown documents by adding chunks like

```
```{python}
import pandas as pd
...
```

However, sublime-ide-r currently does not support respective syntax highlighting. Is it possible to add?

**Comment by randy3k** [comment]
Definitely

**Comment by adibender** [comment]
Great news. I will test as soon as its on package control! 
thx for your effort!

**Comment by randy3k** [comment]
0.1.8 is released

**Comment by adomingues** [comment]
Hi Randy, 

sorry for re-opening this issue, but would it possible to also include highlighting for bash code? Since Rmardown now allows other "engines" other than R, I have been mixing a lot of R and bash and this would make looking at bash code much more pleasant ;) 

Cheers!

**Comment by randy3k** [comment]
Why not? just need to replicate the block and change `python` to `bash`.

**Comment by adomingues** [comment]
Done it and it is working. Cheers :+1:
