### ISSUE TITLE
R-syntax, some ligature symbols not rendered

### ISSUE THREAD

**Issue by kklot** [REditorSupport/sublime-ide-r#27]
using Fira Code or alike, some symbols such as `==`, `<=` are not rendered. These work on plain text or other language. The reason seem to be the ""..syntax breaks the characters into. separate tokens.." as show on [Sublime HQ website](https://www.sublimetext.com/docs/3/ligatures.html).

R
![Screenshot 2019-06-13 at 19 26 41](https://user-images.githubusercontent.com/4459378/59457865-2e118880-8e11-11e9-9ef8-bac8e0cc615b.png)

C++
![Screenshot 2019-06-13 at 19 27 14](https://user-images.githubusercontent.com/4459378/59457897-41bcef00-8e11-11e9-8629-52b9dc82812c.png)

**Comment by randy3k** [comment]
I am not familiar with ligature rendering in Sublime, let me do some researches first.

**Comment by kklot** [comment]
thanks, this info might be useful: when commenting the R code the ligature works.

![Screenshot 2019-06-17 at 19 59 08](https://user-images.githubusercontent.com/4459378/59629302-6c24ea00-913a-11e9-9299-1758e69a3f76.png)

**Comment by randy3k** [comment]
It's been fixed upstream at Sublime Text: https://github.com/sublimehq/Packages
You would need to either wait for the next dev release or clone the updated R syntax from the repo.
