### ISSUE TITLE
Could not start rlang WinErrror 267. The directory name is invalid

### ISSUE THREAD

**Issue by ZeroMorale** [REditorSupport/sublime-ide-r#33]
So this is my user setup

    // path to R, for example
    // (mac, linux): "/usr/local/bin/R"
    // (windows):    "C:\\Program Files\\R\\R-x.y.z\\bin\\R.exe"
    "r_binary": "C:/Program Files/R/R-3.6.1/bin/x64/R.exe",

What seem to be a problem?

**Comment by randy3k** [comment]
Does it work without specifying `r_binary`? R-IDE would try to determine the PATH to R via registry at the first place.

**Comment by ZeroMorale** [comment]
Well, i removed path to R.exe now i keep getting this error: "Language server rlang has crashed, do you want to restart it"?

**Comment by randy3k** [comment]
Could you open LSP settings and switch on `log_debug` and `log_stderr` and open R-IDE settings and switch on `lsp_debug`?

Then restart Sublime Text, open the project and report any error messages in the Sublime console.

**Comment by ZeroMorale** [comment]
Sorry, i  I had it all figured out. Thanks for being cool
