### ISSUE TITLE
New Menu Removes "Set Current Directory"

### ISSUE THREAD

**Issue by dfeng** [REditorSupport/sublime-ide-r#34]
First off, thanks for your libraries. They're the reason why I can keep using ST3 for my main driver.

With the new menu, suddenly my "set current directory" menu has disappeared. I tried to add it myself via `r_ide_exec_items`, except I can't seem to access the previous send_code function. Is this now not possible?

**Comment by randy3k** [comment]
I have removed them from R-IDE to support dynamic menu.

For a workaround now, see this section
https://github.com/randy3k/SendCode/blob/master/README.md#custom-keybindings
for setting up a keybind for changing working directory.

I’d need to figure out a way to allow arbitrary commands.

**Comment by randy3k** [comment]
3f8f037 should address this by using the `menu_items` settings.

**Comment by randy3k** [comment]
v0.2.2 is released. Please allow a while for Package Control to get updated.
