### ISSUE TITLE
R-IDE: No render rmarkdown

### ISSUE THREAD

**Issue by the-Zian** [REditorSupport/sublime-ide-r#35]
Recently I no longer have support for rendering rmarkdown via r-box.
![image](https://user-images.githubusercontent.com/23162852/67858403-7646f400-faef-11e9-8207-b9b25d855a9f.png)

I am running `Sublime Text Version 3.2.2, Build 3211` on `macOS Mojave, Version 10.14.6`.

Can confirm that my `R-IDE.sublime-settings` file still has all of the `exec_items` to fill out the menu, just nothing is showing other than `Exec`.

Let me know what other information I can provide that might be of help.

**Comment by albertostefanelli** [comment]
Same here problem here with the same operating system. I still have the options in the R-IDE but they are not working

**Comment by randy3k** [comment]
Does restarting sublime test help?

**Comment by the-Zian** [comment]
> Does restarting sublime test help?

That worked, thank you!

**Comment by the-Zian** [comment]
> Same here problem here with the same operating system. I still have the options in the R-IDE but they are not working

Check your `R-IDE.sublime-settings`, you might want to change the `Render R Markdown` command to: `rmarkdown::ender('$file', encoding = 'UTF-8')`. I noticed my settings file changed to `$file_name` which doesn't give the full path.

**Comment by randy3k** [comment]
Thanks for the note. I will make a change soon
