### ISSUE TITLE
typo regarding punctuation.definition.raw.code-fence.end.markdown?

### ISSUE THREAD

**Issue by jh-min** [REditorSupport/sublime-ide-r#36]
<img width="426" alt="punc1" src="https://user-images.githubusercontent.com/57447828/69788977-edf96300-1202-11ea-80e3-7c80b79728dc.PNG">  

> scope `punctuation.definition.raw.code-fence.begin.markdown` works

<img width="287" alt="punc2" src="https://user-images.githubusercontent.com/57447828/69788979-edf96300-1202-11ea-9d39-e6e686618ffd.PNG">  

> scope `punctuation.definition.raw.code-fence.end.markdown` not works?  

I am not sure this is a real issue but it seems that ending code fences(```) are not properly captured when current syntax is _R Markdown_ and I accidentally found that there is a typo `capt.ures` instead of `captures` in line [1050](https://github.com/REditorSupport/sublime-ide-r/blob/514918674db9791a296f1c330603802c347d48cb/R%20Markdown.sublime-syntax#L1050) & [1076](https://github.com/REditorSupport/sublime-ide-r/blob/514918674db9791a296f1c330603802c347d48cb/R%20Markdown.sublime-syntax#L1076) of _R Markdown.sublime-syntax_ (though it does not affect punctuation mark capturing when I rectified it using _PackageResourceViewer_).
Sorry if it was intended.

**Comment by randy3k** [comment]
Thank for raising it, I am working on an update.

**Comment by randy3k** [comment]
9a5a67d should fix it.
