### ISSUE TITLE
R code blocks not recognized

### ISSUE THREAD

**Issue by jokorn** [REditorSupport/sublime-ide-r#38]
After the latest package update (current version 0.2.4), the "R Markdown" syntax no longer recognizes R code blocks as R code but instead formats the content as Markdown.

Example:
`````
```{r}
a <- 2
b <- function(x) {
    print(x)
}
# Comment
```
`````

See images...

![scope_markdown](https://user-images.githubusercontent.com/7759201/69949072-10d09380-14f1-11ea-9981-893225c032a1.png)

![syntax](https://user-images.githubusercontent.com/7759201/69949084-17f7a180-14f1-11ea-869a-79004f56d2e7.png)

**Comment by randy3k** [comment]
We have just updated the R markdown syntax. Perhaps you might need to restart Sublime Text? By the way, what version of Sublime Text are you using?

**Comment by randy3k** [comment]
Oh, I know what's going on.

**Comment by jokorn** [comment]
Restart of ST3 unfortunately didn't solve it. My version of Sublime Text 3 is 3.2.2, build 3211.

**Comment by randy3k** [comment]
I accidentally pulled in some changes from upstream which only supports Sublime Text 4.
v0.2.5 should fix it now.

**Comment by jokorn** [comment]
It is fixed with new "R Markdown.sublime-syntax" file. 

Thank you for the quick resolution of this issue and for this great package; I really enjoy authoring .Rmd-files with this syntax in ST3 and running the codeblocks via Hermes (Jupyter IRkernel) with graphic output directly in ST3.
