### ISSUE TITLE
Directory issues? 

### ISSUE THREAD

**Issue by tford9** [REditorSupport/sublime-ide-r#5]
I've installed the package in Sublime as the instructions suggest, but when attempting to build I am getting this error: 

>>> Error: unexpected input in "rmarkdown::render(C:\"
Execution halted
[Finished in 0.6s with exit code 1]
[cmd: ['R.exe', '--slave', '-e', 'rmarkdown::render("C:\\Users\\user\\Desktop\\place1\\place2\\h_1\\h1.Rmd", encoding = "UTF-8")']]
[dir: C:\Users\user\Desktop\place1\place2\h_1]

I've added the R bin to my PATH, and swapped between directly addressing the bin and just relying on the PATH env variable to no avail. Any ideas? The fact that the error message is cut off where it is, makes me think that the function call might be escaping the address, or failing to.

**Comment by randy3k** [comment]
it seems a typical windows issue of escaping backward slashes.

**Comment by randy3k** [comment]
should be fixed by 304538b

**Comment by tford9** [comment]
In the package settings, should the path still look like this?

![delete](https://user-images.githubusercontent.com/6520354/45243456-deba8c80-b2c1-11e8-8f56-bf11f45a27b2.PNG)

**Comment by randy3k** [comment]
Yes

**Comment by tford9** [comment]
Hmm, I'm getting the same error message. I used the package manager to install the first time, but I just cloned the repo (from master) into the packages directory (replacing the old one). Is there a step I'm missing?

**Comment by tford9** [comment]
Apologies, here is the updated error message: 

> Error: unexpected input in "rmarkdown::render(C:\"
Execution halted
[Finished in 0.7s with exit code 1]
[cmd: ['C:\\Program Files\\R\\R-3.5.1\\bin\\R.exe', '--slave', '-e', 'rmarkdown::render("C:\\Users\\user\\Desktop\\place1\\place2\\h1\\h1.Rmd", encoding = "UTF-8")']]
[dir: C:\Users\user\Desktop\place1\place2\h1]

**Comment by randy3k** [comment]
Are you checking out the master branch?

**Comment by tford9** [comment]
Yes, I believe so. 
![image](https://user-images.githubusercontent.com/6520354/45247566-7924cb00-b2d6-11e8-9c59-744d1277307a.png)

**Comment by randy3k** [comment]
Let me check later today.

**Comment by randy3k** [comment]
Please check again. bc743fb39b9a3dcd25dfa92c4664b97d12c28960 should have addressed the issue.
