### ISSUE TITLE
R (3.5.1) Missing Pandocs Error

### ISSUE THREAD

**Issue by tford9** [REditorSupport/sublime-ide-r#7]
My system has these specs:

Windows >= 8 x64 (build 9200)
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

And I am getting this new error: 
> Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).

The problem is that when I attempt to install pandocs, I get this message: 
![image](https://user-images.githubusercontent.com/6520354/45260013-e2750e80-b3a8-11e8-8274-5f50a85a7abe.png)

It is likely that making a Sys.setenv(RSTUDIO_PANDOCS="PATH") before the rendering calls could fix the issue.

**Comment by randy3k** [comment]
pandoc is not a R package, you could download it from https://pandoc.org/. You may also make use of the pandoc shipped by RStudio by setting `RSTUDIO_PANDOCS` to where the binary is located.

**Comment by tford9** [comment]
Adding the `RSTUDIO_PANDOCS` environmental variable in Windows fixed this problem for me.
