### ISSUE TITLE
Disable higlighting in code from the linter

### ISSUE THREAD

**Issue by emilBeBri** [REditorSupport/sublime-ide-r#9]
Maybe it's just me, but I can't seem to find a preference setting that disable the suggestions for linter? I'd like to see the suggestions in the bar below the R-script, but the highligtning with underline and the dot at the side is too distracting. How do I come about disabling this?

**Comment by randy3k** [comment]
It is not yet documented, but you could specify the following settings in LSP to turn on the linter.

```
{
	"clients":
	{
		"rlang":
		{
			"enabled": true,
			"settings":{
				"diagnostics": false
			}
		}
	}
}
```

Or you could disable the specific linter as shown [here](https://github.com/REditorSupport/languageserver#diagnostics-settings)

**Comment by emilBeBri** [comment]
ah yes of course, I was looking at the settings for the languageserver... my fault, sorry for the interruption, thank you for the answer.
